# How to run:
# 1. cd server
# 2. docker-compose up -d
#
# To stop:
# docker-compose down
#
# To check logs:
# docker-compose logs -f
#
version: '3.8'

name: v-label

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: vlabel_user
      POSTGRES_PASSWORD: vlabel_password
      POSTGRES_DB: vlabel_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vlabel_user -d vlabel_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
